### PR TITLE
Remove pytest from published dependencies (now dev only)

### PR DESCRIPTION
**Pull request by mmindenhall**
Hi,

I'm seeing this error when I add your project to my list of dependencies:

```shell
ERROR: Cannot install pickpack==1.0.0 and pytest==7.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pytest==7.2.1
    pickpack 1.0.0 depends on pytest<7.0 and >=6.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

The error is due to pytest being in both runtime (`[tool.poetry.dependencies]`) and dev (`[tool.poetry.dev-dependencies]`) dependencies in the `pyproject.toml` file.  This PR simply removes pytest from `[tool.poetry.dependencies]`.  If you accept this PR and publish a new version, this should resolve the error.

Thanks for your hard work on the project!

### CODE REVIEW

**Comment by mmindenhall** [comment]
Hi @anafvana, is this something you can get merged soon?  This is holding me up from upgrading to the latest pytest version on my project.  Thanks!

**Comment by gc-av** [comment]
Hey @mmindenhall,
I'm so sorry I didn't see your PR before! Give me a few minutes and I'll review it and merge if everything is alright

**Comment by mmindenhall** [comment]
Thanks @anafvana!  Would it be possible to also make a new 1.0.1 release with this change in pypi.org?

**Comment by gc-av** [comment]
@mmindenhall I noticed that my pipeline is failing, so I just wanna look into what the issue is (which I suspect is it being set up to use the prod environment for running the tests, but I haven't touched this code in a few months) before I publish a new version. I'm planning to do this over the weekend, but if I don't, feel free to ping me on Monday!

**Comment by gc-av** [comment]
@mmindenhall Sorry I ended up disappearing. I'm finally back and the new release is out, with all the necessary corrections!

**Pull request merged**
